In [73]:
text = "The first time you see The Second Renaissance it may look boring. Look at it at least twice and definitely watch part 2. It will change your view of the matrix. Are the human people the ones who started the war ? Is AI a bad thing ?"
print(text)

The first time you see The Second Renaissance it may look boring. Look at it at least twice and definitely watch part 2. It will change your view of the matrix. Are the human people the ones who started the war ? Is AI a bad thing ?


In [74]:
# Convert to lowercase
text = text.lower()
print(text)

the first time you see the second renaissance it may look boring. look at it at least twice and definitely watch part 2. it will change your view of the matrix. are the human people the ones who started the war ? is ai a bad thing ?


In [75]:
# Remove punctuation characters
import re
text = re.sub(r"[^a-zA-Z0-9]"," ",text)
text = re.sub(r"^\d+\s|\s\d+\s|\s\d+$", "", text)
print(text)

the first time you see the second renaissance it may look boring  look at it at least twice and definitely watch part it will change your view of the matrix  are the human people the ones who started the war   is ai a bad thing  


In [76]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [77]:
# import statements
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

In [78]:
# Split text into words using NLTK
words = word_tokenize(text)
print(words)

['the', 'first', 'time', 'you', 'see', 'the', 'second', 'renaissance', 'it', 'may', 'look', 'boring', 'look', 'at', 'it', 'at', 'least', 'twice', 'and', 'definitely', 'watch', 'part', 'it', 'will', 'change', 'your', 'view', 'of', 'the', 'matrix', 'are', 'the', 'human', 'people', 'the', 'ones', 'who', 'started', 'the', 'war', 'is', 'ai', 'a', 'bad', 'thing']


In [79]:
# Split text into sentences using NLTK
words = sent_tokenize(text)
print(words)

['the first time you see the second renaissance it may look boring  look at it at least twice and definitely watch part it will change your view of the matrix  are the human people the ones who started the war   is ai a bad thing']


In [80]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [81]:
# import statements
from nltk.corpus import stopwords
import re
from nltk.tokenize import word_tokenize

In [82]:
# remove stop wors
words = [w for w in words if w not in stopwords.words("english")]
print(words)

['the first time you see the second renaissance it may look boring  look at it at least twice and definitely watch part it will change your view of the matrix  are the human people the ones who started the war   is ai a bad thing']


In [83]:
print(stopwords.words("english"))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [84]:
nltk.download('words')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!


True

In [85]:
#  import statements
from nltk import pos_tag
from nltk import ne_chunk

In [86]:
# tokenize text
sentence = word_tokenize(text)
# tag each word with part of speech
pos_tag(sentence)

[('the', 'DT'),
 ('first', 'JJ'),
 ('time', 'NN'),
 ('you', 'PRP'),
 ('see', 'VBP'),
 ('the', 'DT'),
 ('second', 'JJ'),
 ('renaissance', 'NN'),
 ('it', 'PRP'),
 ('may', 'MD'),
 ('look', 'VB'),
 ('boring', 'JJ'),
 ('look', 'NN'),
 ('at', 'IN'),
 ('it', 'PRP'),
 ('at', 'IN'),
 ('least', 'JJS'),
 ('twice', 'RB'),
 ('and', 'CC'),
 ('definitely', 'RB'),
 ('watch', 'VB'),
 ('part', 'NN'),
 ('it', 'PRP'),
 ('will', 'MD'),
 ('change', 'VB'),
 ('your', 'PRP$'),
 ('view', 'NN'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('matrix', 'NN'),
 ('are', 'VBP'),
 ('the', 'DT'),
 ('human', 'JJ'),
 ('people', 'NNS'),
 ('the', 'DT'),
 ('ones', 'NNS'),
 ('who', 'WP'),
 ('started', 'VBD'),
 ('the', 'DT'),
 ('war', 'NN'),
 ('is', 'VBZ'),
 ('ai', 'RP'),
 ('a', 'DT'),
 ('bad', 'JJ'),
 ('thing', 'NN')]

In [ ]:
# tokenize, pos tag, then recognize named entities in text
tree = ne_chunk(pos_tag(word_tokenize(text)))
print(tree)

(S
  the/DT
  first/JJ
  time/NN
  you/PRP
  see/VBP
  the/DT
  second/JJ
  renaissance/NN
  it/PRP
  may/MD
  look/VB
  boring/JJ
  look/NN
  at/IN
  it/PRP
  at/IN
  least/JJS
  twice/RB
  and/CC
  definitely/RB
  watch/VB
  part/NN
  2/CD
  it/PRP
  will/MD
  change/VB
  your/PRP$
  view/NN
  of/IN
  the/DT
  matrix/NN
  are/VBP
  the/DT
  human/JJ
  people/NNS
  the/DT
  ones/NNS
  who/WP
  started/VBD
  the/DT
  war/NN
  is/VBZ
  ai/RP
  a/DT
  bad/JJ
  thing/NN)


In [ ]:
# Define a custom grammar that includes the missing words
my_grammar = nltk.CFG.fromstring("""
  S -> NP VP
  PP -> P NP
  NP -> Det N | Det N PP | 'I' | 'you' | 'it' | Det ADJ N | N
  VP -> V NP | VP PP | V | V ADJ | V N | V Det N
  Det -> 'an' | 'my' | 'the' | 'your' | 'a' | '2'
  N -> 'elephant' | 'pajamas' | 'time' | 'renaissance' | 'part' | 'view' | 'matrix' | 'people' | 'ones' |'war' | 'thing' | 'first' | 'second' | 'human' | 'ai'
  V -> 'shot' | 'see' | 'look' | 'watch' | 'change' | 'started' | 'is' | 'may' | 'are' | 'will'
  ADJ -> 'boring' | 'bad' | 'least' | 'twice' | 'watch' | 'change' | 'started' | 'definitely'
  P -> 'in' | 'at' | 'of' | 'who' | 'and'
  """)
# The code above adds all the missing words to the grammar.
# Some rules have been updated to reflect relationships between the new words.
# For example, 'your' has been added to Det and 'human' and 'ai' have been added to N.
# You may need to further refine these rules and add new rules to improve the parsing accuracy.


parser = nltk.ChartParser(my_grammar)

for tree in parser.parse(sentence):
  print(tree)

In [ ]:
for tree in parser.parse(sentence):
    print(tree)

In [ ]:
nltk.download('wordnet') # download for lemmatization

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
text = "The first time you see The Second Renaissance it may look boring. Look at it at least twice and definitely watch part 2. It will change your view of the matrix. Are the human people the ones who started the war ? Is AI a bad thing ?"

# Normalize text
text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower())

# Tokenize text
words = text.split()
print(words)

['the', 'first', 'time', 'you', 'see', 'the', 'second', 'renaissance', 'it', 'may', 'look', 'boring', 'look', 'at', 'it', 'at', 'least', 'twice', 'and', 'definitely', 'watch', 'part', '2', 'it', 'will', 'change', 'your', 'view', 'of', 'the', 'matrix', 'are', 'the', 'human', 'people', 'the', 'ones', 'who', 'started', 'the', 'war', 'is', 'ai', 'a', 'bad', 'thing']


In [ ]:
# Remove stop words
words = [w for w in words if w not in stopwords.words("english")]
print(words)

['first', 'time', 'see', 'second', 'renaissance', 'may', 'look', 'boring', 'look', 'least', 'twice', 'definitely', 'watch', 'part', '2', 'change', 'view', 'matrix', 'human', 'people', 'ones', 'started', 'war', 'ai', 'bad', 'thing']


In [ ]:
from nltk.stem.porter import PorterStemmer

# Reduce words to their stems
stemmed = [PorterStemmer().stem(w) for w in words]
print(stemmed)

['first', 'time', 'see', 'second', 'renaiss', 'may', 'look', 'bore', 'look', 'least', 'twice', 'definit', 'watch', 'part', '2', 'chang', 'view', 'matrix', 'human', 'peopl', 'one', 'start', 'war', 'ai', 'bad', 'thing']


In [ ]:
from nltk.stem.wordnet import WordNetLemmatizer

# Reduce words to their root form
lemmed = [WordNetLemmatizer().lemmatize(w) for w in words]
print(lemmed)

['first', 'time', 'see', 'second', 'renaissance', 'may', 'look', 'boring', 'look', 'least', 'twice', 'definitely', 'watch', 'part', '2', 'change', 'view', 'matrix', 'human', 'people', 'one', 'started', 'war', 'ai', 'bad', 'thing']


In [ ]:
# Lemmatize verbs by specifying pos
lemmed = [WordNetLemmatizer().lemmatize(w, pos='v') for w in lemmed]
print(lemmed)

['first', 'time', 'see', 'second', 'renaissance', 'may', 'look', 'bore', 'look', 'least', 'twice', 'definitely', 'watch', 'part', '2', 'change', 'view', 'matrix', 'human', 'people', 'one', 'start', 'war', 'ai', 'bad', 'thing']


In [ ]:
corpus = ["The first time you see The Second Renaissance it may look boring.",
        "Look at it at least twice and definitely watch part 2.",
        "It will change your view of the matrix.",
        "Are the human people the ones who started the war?",
        "Is AI a bad thing ?"]

In [ ]:
stop_words = stopwords.words("english")
lemmatizer = WordNetLemmatizer()

In [ ]:
def tokenize(text):
    # normalize case and remove punctuation
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower())

    # tokenize text
    tokens = word_tokenize(text)

    # lemmatize andremove stop words
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# initialize count vectorizer object
vect = CountVectorizer(tokenizer=tokenize)

In [ ]:
# get counts of each token (word) in text data
X = vect.fit_transform(corpus)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0]])

In [ ]:
# view token vocabulary and counts
vect.vocabulary_

{'first': 6,
 'time': 20,
 'see': 17,
 'second': 16,
 'renaissance': 15,
 'may': 11,
 'look': 9,
 'boring': 3,
 'least': 8,
 'twice': 21,
 'definitely': 5,
 'watch': 24,
 'part': 13,
 '2': 0,
 'change': 4,
 'view': 22,
 'matrix': 10,
 'human': 7,
 'people': 14,
 'one': 12,
 'started': 18,
 'war': 23,
 'ai': 1,
 'bad': 2,
 'thing': 19}

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

# initialize tf-idf transformer object
transformer = TfidfTransformer(smooth_idf=False)

In [ ]:
# use counts from count vectorizer results to compute tf-idf values
tfidf = transformer.fit_transform(X)

In [ ]:
# convert sparse matrix to numpy array to view
tfidf.toarray()

array([[0.        , 0.        , 0.        , 0.36419547, 0.        ,
        0.        , 0.36419547, 0.        , 0.        , 0.26745392,
        0.        , 0.36419547, 0.        , 0.        , 0.        ,
        0.36419547, 0.36419547, 0.36419547, 0.        , 0.        ,
        0.36419547, 0.        , 0.        , 0.        , 0.        ],
       [0.39105193, 0.        , 0.        , 0.        , 0.        ,
        0.39105193, 0.        , 0.        , 0.39105193, 0.28717648,
        0.        , 0.        , 0.        , 0.39105193, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.39105193, 0.        , 0.        , 0.39105193],
       [0.        , 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# initialize tf-idf vectorizer object
vectorizer = TfidfVectorizer()

In [ ]:
# compute bag of word counts and tf-idf values
X = vectorizer.fit_transform(corpus)

In [ ]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.30298183, 0.        , 0.        , 0.30298183, 0.        ,
        0.        , 0.20291046, 0.        , 0.24444384, 0.        ,
        0.30298183, 0.        , 0.        , 0.        , 0.        ,
        0.30298183, 0.30298183, 0.30298183, 0.        , 0.40582093,
        0.        , 0.30298183, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.30298183, 0.        ],
       [0.        , 0.30015782, 0.        , 0.60031564, 0.        ,
        0.        , 0.        , 0.30015782, 0.        , 0.        ,
        0.        , 0.20101919, 0.30015782, 0.24216544, 0.        ,
        0.        , 0.        , 0.        , 0.30015782, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.30015782, 0.        , 0.        ,
        0.30015782, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.